name: Node.js CI
on: [pull_request]
permissions:
  contents: read
jobs:
  node:
    uses: quokkify/project-toolkit/.github/workflows/node-ci.yml@a64c987642f25d81e6bc3531336225fcde0ba4d5 # v2.22.0
    with:
      package-manager: npm
      lint-command: npm run lint
      test-command: npm test
